name: CI

on:
    push:
        branches:
            - master
            - winter*
            - spring*
            - summer*
    pull_request:
    workflow_call: # Allows this workflow to be used by the release workflow

jobs:
    build:
        name: Build (jest@${{ matrix.jest-version }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                jest-version: ['local', '28', '29']
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6
              with:
                  node-version: '20.20.1'

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies w/ jest@${{ matrix.jest-version }}
              if: matrix.jest-version != 'local'
              run: yarn add jest@${{ matrix.jest-version }} jest-environment-jsdom@${{ matrix.jest-version }} -W --dev

            - name: Install dependencies w/ local jest
              if: matrix.jest-version == 'local'
              run: yarn install --frozen-lockfile

            - name: Run linter
              run: yarn lint

            - name: Check format
              run: yarn format:check

            - name: Run unit tests
              run: yarn test --runInBand
